# Generated by Django 4.0.1 on 2022-01-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='headline',
            field=models.CharField(blank=True, max_length=256, verbose_name='Titre'),
        ),
    ]
