# Generated by Django 4.0.1 on 2022-01-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='headline',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Description'),
        ),
    ]
