# Generated by Django 4.0.1 on 2022-01-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review_review_from_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='book_name',
            field=models.CharField(max_length=256, verbose_name='book_name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.CharField(blank=True, max_length=2048, verbose_name='content'),
        ),
    ]
