# Generated by Django 4.0.1 on 2022-01-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ticket_book_name_alter_ticket_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author_book',
            field=models.CharField(blank=True, max_length=256, verbose_name='author_name'),
        ),
    ]
