# Generated by Django 4.0.1 on 2022-01-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_book',
            field=models.CharField(blank=True, max_length=256, verbose_name='author_name'),
        ),
    ]
