# Generated by Django 4.0.1 on 2022-01-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='advised',
            field=models.BooleanField(default=False, verbose_name='advised'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_name',
            field=models.CharField(max_length=256, verbose_name='book_name'),
        ),
    ]
