# Generated by Django 4.0.1 on 2022-01-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_review_advised_alter_review_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='uploader',
        ),
        migrations.AlterField(
            model_name='review',
            name='advised',
            field=models.BooleanField(default=False, verbose_name='Recommandé'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_book',
            field=models.CharField(blank=True, max_length=256, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_name',
            field=models.CharField(max_length=256, verbose_name='nom du livre'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=8192, verbose_name='Votre avis'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='author_book',
            field=models.CharField(blank=True, max_length=256, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='book_name',
            field=models.CharField(max_length=256, verbose_name='Nom du livre'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Information demandé (facultatif)'),
        ),
    ]
