# Generated by Django 4.0.1 on 2022-01-07 10:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ticket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='advised',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author_book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_from_ticket',
        ),
        migrations.AddField(
            model_name='review',
            name='headline',
            field=models.CharField(default='rien', max_length=256, verbose_name='Titre de la Review'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='app.ticket'),
            preserve_default=False,
        ),
    ]
