# Generated by Django 4.0.1 on 2022-01-07 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ticket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='advised',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default='vide', max_length=256, verbose_name='Titre de la Review'),
            preserve_default=False,
        ),
    ]
